### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [vishy1618/gcm#6]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by vishy1618** [comment]
Yes, working on dropping this and using serde instead.

**Comment by vishy1618** [comment]
Moved to serde with https://github.com/vishy1618/gcm/commit/fd3bba1d96a939256762457c9c2c8479d935199c! Will be releasing a new crate soon.

**Comment by vishy1618** [comment]
Released 0.2.0 with rustc-serialize dependency removed.
